Change dockerfile to download release.
ranking-agent/api-watchdog-translator-tests pull request #14
Opened 2022-03-01 17:10 UTC by kennethmorton

Upgraded image to renciorg python image and removed the need to publish api-watchdog to pypi. This will require that we update these tests when we create a new release of api-watchdog.

2022-03-01 17:51 UTC, maximusunc requested changes

2022-03-01 17:51 UTC, maximusunc commented on Dockerfile
> +RUN pip install .
I think this needs to be `RUN pip install .[TRAPI]` to enable TRAPI validation (assuming this is run in bash. If zsh, you need to wrap the `.[TRAPI]` in quotes).

2022-03-01 17:55 UTC, maximusunc approved these changes

2022-03-01 18:00 UTC, kennethmorton commented on Dockerfile
> +RUN pip install .
Good catch!

2022-03-02 18:57 UTC, PhillipsOwen approved these changes
looks good...

2022-03-02 20:22 UTC, merged